#+title: Project: Intersection Density for Transitive Permutation Groups
#+DATE: 2026-05-13
#+DESCRIPTION: Cataloguing intersection densities and relevant group data for transitive permutation groups.
#+FILETAGS: :programming:math:groups:
#+TOC: headlines 2

* Overview
This post discusses my [[https://intersection-density.vercel.app][database]] of intersection densities for small
transitive permutation groups. I spent two summers (2024/2025) working
on this project as an NSERC USRA student, under the supervision of
[[https://uregina.ca/~meagherk/][Dr. Karen Meagher]]. I recently gave a talk on this subject at the
2026 Prairie Discrete Mathematics Workshop, and this blog post aims
to answer the same 'what worked and what didnt?' question that my
talk focused on.

Throughout this post, I may refer to simply 'a group', but I always
mean 'transitive permutation group'.

* Intersection Density
Let \([n] = \{1,2,\ldots,n\}\). Given two permutations \(\sigma, \pi \in \text{Sym}([n])\), we say that
\(\sigma\) and \(\pi\) /are intersecting/ if there exists \(i,j \in [n]\) such that
\[
        \sigma(i) = \pi(i) = j
\]
Given a set of permutations, we say that the set is /intersecting/ if any two elements from the set are intersecting
as above.

Let \(G \leq \text{Sym}([n])\) be a transitive permutation group. For an intersecting set \(\mathcal{F} \subseteq G\)
(/not necessarily a subgroup, but it can be!/), the /intersection density/ of $\mathcal{F}$ is defined as
\[
        \rho(\mathcal{F}) := \frac{|\mathcal{F}|}{|G_i|}
\]
Where $G_i$ is the stabilizer of the point $i$ in the group $G$. Using this, the /intersection density/ of the group $G$
is defined as
\[
        \rho(G) := \max \left\{\frac{|\mathcal{F}|}{|G_i} \mid \mathcal{F} \text{ is intersecting}\right\}
\]

This was first defined in 2020 by Li, Song and Pantangi.

The first basic observation we can make is that /$\rho(G)$ is bounded below by 1/. This is because
we can always pull the stabilizer of a point out of a transitive group (and it will have order $\frac{|G|}{n}$).
A profound result by [[https://arxiv.org/abs/2009.01086][Razafimahatratra, Meagher, Spiga]] shows that for $n>2$, $\rho(G)$ is /bounded
above by $\frac{n}{3}$/. Their approach came from the graph-theoretic formulation of the problem, in terms of
the /derangement graph/. With these two results, we now have cheap-and-easy bounds for the possible values of
$\rho(G)$ in terms of $n$, namely
\[
        1 \leq \rho(G) \leq \frac{n}{3}
\]
But what is a derangement graph? and how do we calculate $\rho(G)$ precisely?

** Derangement Graphs
Again, let $G\leq\text{Sym}([n])$ be a transitive group. The /derangement graph of $G$/, denoted $\Gamma_G$,
is an undirected graph whose
- vertices are elements of the group, and
- two vertices $\sigma, \pi$ are adjacent if $\sigma \pi^{-1}$ has /no fixed points/.
Keen-eyed readers will recognize this as a Cayley graph whose connection set is the derangments of the group.
It turns out that the size of the largest intersecting set in $G$ corresponds to the /size of a maximum coclique/
(independence number) of $\Gamma_G$. Then we can restate our problem as
\[
        \rho(G) = \frac{\alpha(\Gamma_G)}{|G_i|}
\]
So, calculating intersection density amounts to finding the largest coclique in the graph. You might say
"Finding the independence number of a graph is NP-Complete; where does this even get us?" To which I would
respond "you are correct; actually very far!" In the next section (which I hope to write soon) I will take you
through what turned out to be the most efficient methods for computing $\rho(G)$, all of which pertain to the
derangement graph.

* Computational Methods
TODO

* Interesting patterns
TODO
